//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantDAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Images
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> PlantID { get; set; }
        public Nullable<System.Guid> JournalID { get; set; }
        public string ImageFilePath { get; set; }
    
        public virtual Journal Journal { get; set; }
        public virtual Plant Plant { get; set; }
    }
}
