//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantDAL.EDMX
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PlantTrackerDBEntities : DbContext
    {
        public PlantTrackerDBEntities()
            : base("name=PlantTrackerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<CustomValues1> CustomValues1 { get; set; }
        public virtual DbSet<CustomValues2> CustomValues2 { get; set; }
        public virtual DbSet<CustomValues3> CustomValues3 { get; set; }
        public virtual DbSet<CustomValues4> CustomValues4 { get; set; }
        public virtual DbSet<CustomValues5> CustomValues5 { get; set; }
        public virtual DbSet<Images> Images { get; set; }
        public virtual DbSet<Journal> Journal { get; set; }
        public virtual DbSet<Plant> Plant { get; set; }
    }
}
